LOG1222

Currently Watching/Paused:
× Gosick (S1E1) 

(⁠个⁠_⁠个⁠)

Anime Watched: (200+)

- Konosuba (S3)
- Redo of Healer (S2)
- Evangelion
- The Familiar Of Zero
- Yosuga no sora
- Golden Time
- Clannad
- This Art Club Has A Problem (S2)
- Masamune kun no revenge 
- Attack on Titan  
- Overlord (S5) 
- Akame ga kill  
- Love, chunibyo & other delusions 
- The saga of tanya the evil (S2)
- The Misfit of Demon Lord Academy (S2)
- Classroom of the elite (S3) 
- Sword Art Online (S5)
- Kokoro Connect
- Gate (S3) 
- Charlotte 
- Little Busters 
- Rewrite
- Re Zero (S3) 
- Date A Live (S5)
- A Silent Voice (Movie)
- Eminence in Shadow 
- Assassin's Pride (S2)
- Cautious Hero (S2)
- I'm standing on a million lives (S3) 
- Yosuga no sora
- Henneko 
- Angel Beats

◉⁠‿

MAIN SECTION:
 
- A Bridge to the Starry Skies
- A rascal doesn't dream of a bunny girl senpai (S2)
- Absolute Duo (S2)
- Akashic Records of Bastard Magic Instructor (S2)
- Amagami SS
- Anohana
- Ao-chan Can't Study
- Armed girl's machiavellism (S2)
- Arifureta: From Commonplace to World's Strongest (S3 & OVA)
- Aura: Koga Maryuin's Last War (Movie)
- Banished from the Hero's Party (S2)
- Banished from the Hero’s Party, I decided to live a quiet life in the Countryside (S2)
- Beyond the boundary (S2)
- Black Bullet
- Bladedance of Elementalers (S2)
- Boarding School Juliet (S2)
- Bubble up like soda pop (Movie)
- Call of the night (S2)
- Campione (S2)
- Classroom Crisis (S2)
- Combatants will be dispatched (S2)
- Chivalry of a failed knight
- Danmachi (S4)
- Darling in the Franxx (S2)
- Death march to the parallel world rhapsody (S2)
- Demon King Daimao
- Dog Days (S2)
- Domestic Girlfriend
- Dragonar Academy (S2)
- Eromanga Sensei (S2)
- Gamers! (S2)
- Genocidal Organ (Movie)
- Hello World (Movie)
- Hensuki (S2)
- Highschool DXD (S5)
- Highschool of the dead
- How a realist hero rebuilt the kingdom (S3)
- How not to summon a demon lord (S3)
- Hyouka
- I Want To Eat Your Pancreas (Movie)
- I'm Quitting Heroing
- If Her Flag Breaks
- In Another World With My Smartphone (S2)
- In/Spectre (S3)
- Infinite Stratos (S3)
- Invaders of the Rokujouma!? (S2)
- Josee (Movie)
- Kissxsis
- Lord Marksman and Vanadis (S2)
- Love, Election and Chocolate
- Magical Warfare (S2)
- Mashiroiro symphony
- Masamune kun no revenge r
- Masamune-kun revenge (S2)
- Mayoi Neko Overrun (S2)
- Mushoku tensei: Jobless Reincarnation (S1 PT 2)
- My Stepmom's daughter is my Ex (S2)
- My Sweet Tyrant
- My Wife is the Student Council President
- My Youth Romantic Comedy Is Wrong, As I Expected (S4)
- Nisekio (S3)
- No game No life (S2)
- Noucome
- Nyaruko: Crawling with Love
- Oreimo: My little sister can't be this cute
- Osamake (S2)
- Our last crusade or the rise of a new world (S2)
- Outbreak Company (S2)
- Over the sky (Movie)
- Oreshura: My Girlfriend and Childhood Friend Fight Too Much
- Photo Kano
- Plastic Memories
- Plunderer (S2)
- Re Zero (S3)
- Remake our life (S2)
- School Days
- Shikimori's Not Just a Cutie (S2)
- Shomin Sample (S2)
- Sky wizards academy (S2)
- Snow White with the Red Hair (S3)
- Spirit Chronicles (S2)
- Tamako Love Story (Movie)
- Teasing Master takagi-san (S4)
- The 8th son are you kidding me?! (S2)
- The Irregular at Magic High School (S3)
- The Master of Ragnarok & Blesser of Einherjar (S2)
- The Quintessential Quintuplets
- The Rising of the Shield hero (S3)
- The asterisk war (S3)
- The Comic Artist and His Assistants (S2)
- The detective is already dead (S2)
- The forest of fireflies (Movie)
- The genius prince's guide to raising a nation out of debt (S2)
- The hidden dungeon only I can enter (S2)
- The moon is beautiful (Movie)
- The strongest sage with the weakest crest (S2)
- The world's finest assassin gets reincarnated in another world as an aristocrat (S2)
- To Every You, I've Loved Before (Movie)
- To Love Ru (S5)
- Tomo Chan is a girl
- Tonikawa: Fly me to the moon (S2)
- Toradora
- Trinity Seven (S2)
- Twin Star Exorcists (S2)
- Undefeated Bahamut Chronicle (S2)
- Unlimited fafnir (S2)
- Wise Man's Grandchild (S2)
- WorldBreak: Aria of Curse for a Holy Swordsman (S2)
- Zipang (S2)
- A Sister's All You Need (S2)
- Weathering With You (Movie)
- When Supernatural Battles Became Commonplace (S2)
- White Album 2
- Your Name. (Movie)
- The Ryuo's Work is Never Done!
- The greatest demon lord is reborn as a typical nobody
- The hentai prince and the stony cat
- The devil is a part-timer (S3)
- The Promised Neverland

FAVORITE VN GAMES: 

- If my heart had wings
- How to raise a happy neet
- Bottle Biosphere
- Katawa Shoujo
- Teaching Life
- Dog Princess
- Lost Life
- DDLC 

(⁠个⁠_⁠个⁠)
 
Watchlist: (150+)
 
NTS: Got these from youtube/fb clips

- My tiny senpai
- Suicide Squad Isekai
- Our Dating Story
- Grancrest Senki
- Frieren: Beyond Journey's End
- A journey through another world: Raising kids while adventuring
- I'm giving the disgraced noble lady I rescued a crash course in naughtiness
- The apothecary diaries
- ReLife
- Kotoura-san
- Goblin Slayer
- Hugarashi
- Iroduku: The World in Colors
- That Time I Got Reincarnated as a Slime
- SPY x FAMILY
- My Isekai Life
- My Instant Death Ability Is So Overpowered
- Engage Kiss
- 3D Kanojo Girl
- Kaguya sama: Love is war
- I'm quitting heroing
- Dear sisters
- Solo Leveling
- When will Ayumu make his Move?
- The world god only knows
- Seven Senses of the Reunion
- Vermeil in gold
- The Disappearance of Nagato Yuki-chan
- Bloodivores
- Gridman Universe
- Haikyu! (P2)
- Tomodachi
- Haganai
- Servant x Service
- Clockwork Planet
- Memoir of Vanitas
- Engaged to the Unidentified
- Love Live
- Steins Gate
- We never learn
- Aharen san wa hakarenai
- Battle game in 5 seconds
- Garden of words
- Archenemy & Hero
- Immoral Guild
- UQ Holder
- Sweetness and Lightning
- Reincarnated as a sword
- Yamada kun and the seven witches
- 5 centimeters per second (Movie)
- Banished from the Hero’s Party, I decided to live a quiet life in the Countryside (S2)
- Renai Flops
- Love is hard for Otaku
- Trapped in a Dating Sim
- More than a married couple but not lovers
- Monogatari
- Bocchi the rock
- Eighty Six
- Buddy Daddies
- Reborn to Master the Blade
- The Beast Tamer
- Ningen Fushin: Adventurers Who Don't Believe in Humanity Will Save the World
- Kubo won’t let me be invisible
- Zom100 Bucket List
- Farming Life in Another World
- The Girl I like forgot her glasses
- Berserker
- Mysterious Girlfriend X
- Dont toy with me Ms. Nagatoro
- Blue Spring Ride
- A day before us
- Chillin in my 30’s
- Bottom character tomozaki
- Her Blue Sky
- Maquia
- Grave of fireflies
- The garden of words
- Children of the sea
- The Iceblade Sorcerer Shall Rule the World
- I Can't Understand What My Husband is Saying
- I've always liked you
- The yakuza's guide to babysitting
- ReLife
- Kimi no todoke 
- Tada never falls in love
- My Senpai is Annoying
- Hell's Paradise
- Oshi no ko
- Summoned to Another World... Again?
- Mashle Magic and Muscles
- Yamada kun to lvl 999
- My Home Hero
- Heavenly delusion
- The angel next door spoils me rotten
- Galaxy next door
- The 100 Girlfriends Who Really, Really, Really, Really, Really Love You
- The ancient magus bride
- Insomniacs after school
- Violet Evergarden
- The Dangers in my Heart
- Uncle from Another world
- The legendary hero is dead
- Skip and Loafer
- My clueless first friend
- The dawn of the witch
- Skeleton knight in another world
- Please take my brother away
- The Anthem of the heart
- Science Fell in Love, So I Tried to Prove It
- Hero Classroom
- Gleipnir
- The money of soul and possibility control
- Witch Craft Works
- Kamikatsu
- Dead mount death play
- what the hell are you here teacher
- Shimoneta: A Boring World Where the Concept of Dirty Jokes Doesn't Exist
- Record of Grancrest War
- Handyman Saitou in another world
- Drugstore in another world
- Nananana's buried treasure
- The tunnel to summer the exit of goodbyes
- Lookism
- Dies Irae
- Tsukimichi: Moonlit Fantasy
- Is the order a rabbit
- Megami no cafe terrace
- Saint cecilia and pastor lawrence
- The dreaming boy is a realist
- Liar Lair
- Onimai
- Horimiya
- An archdemon's dilemma how to love your elf bride
- Love Is Indivisible by Twins
- Idol Pride
- Sasaki to Pi-chan
- Futari bun no shoumei 
- Chained soldier
- The foolish angel dances with devil
- Ro Kyu Bo
- Dance in the vampire bund
- Shakugan no Shana
- If my wife becomes an elementary school student
- Love is individible by twins
- Alya sometimes hides her feelings in russian
- POMPO the cinephile
- Pseudo Harem
- Yozakura Family
- Gushing Over Magical Girls
- My deer friend
- Lull of the sea
- ATRI; My dear moments 
- Nichijou

(⁠个⁠_⁠个⁠)

Currently Watching/Paused: 
× Queen of Tears (S2 E14, E15, E16)

Watchlist:
- The Madela Catalogue 
- Extraordinary You
- Rwby
- Avengers: Age of Ultron
- My Adventures with Superman

Movies & Shows & Primetime Series:
- Adventure Time
- Alive
- All of us are dead
- Alice in borderland
- A quiet place
- A quiet place day one
- Alvin and the chipmunks: Chipwrecked
- Amazing Digital Circus
- Amphibia
- Ant man
- Arrival
- Army of the Dead
- Avatar: The Last Airbender
- Avengers Civil War
- Avengers Endgame
- Avengers Infinity War
- Badland Hunters
- Big City Greens
- Big Hero 6
- Bird Box
- Bird Box Barcelona
- Black Adam
- Black Panther
- Bunny Drop Live Action
- Boss Baby & Boss Baby Family Business
- Cargo
- Charlie and the chocolate factory
- Chip n' Dale: Rescue Rangers
- Cooties
- Dawn of the dead
- Dawn of the planet of the apes
- Deadpool 1 & 2
- Deadpool & Wolverine
- Despicable me rise of gru
- Eli
- Five nights at freddy movie
- Free Guy
- Fallout TV Series
- Freelance
- Furiosa: A Mad Max Saga
- Godzilla vs Kong
- Godzilla x Kong: The New Empire
- Godzilla Minus One
- Gravity Falls
- Guardians of the Galaxy 1 & 2 & 3
- Hotel Transylvania 1 & 2 & 3
- Hunger Games
- I am legend
- I am a hero
- Inception
- Inuyashiki
- Incantation
- Inside and Out
- Jumanji
- Kingdom
- Lightyear
- Little Monsters
- Lost City
- Lucifer
- Midway 2019
- Mischievous Kiss Love in Tokyo
- MrBean's Holiday
- My Love From Another Star
- Ninjago
- Overlord 
- Oblivion
- Patient Zero
- Parasyte Part 1
- Parasyte Part 2
- Parasyte: The Grey
- Peaky Blinders
- Peninsula
- Regular Show
- Rango
- Rio 1 & 2
- Ruby Gillman, Teenage Kraken
- Scouts Guide to the Zombie Apocalypse
- haun of the dead
- Shazam
- Shazam Fury of the Gods
- Shrek 1 & 2 & 3 & 4
- Scary Movie 1 & 2 & 3 & 4 & 5
- Sing 1 & 2
- Smile
- Spiderman: Homecoming
- Spiderman: No Way Home
- Sponge on the Run
- Star vs the forces of evil
- Steven Universe
- Sweet Home 
- The Odd Family: Zombie on Sale
- Trolls
- Trolls Band Together
- Trolls World Tour
- The Amazing Spiderman 1 & 2
- The Avengers
- The Bad Guys
- The Boys Season 5
- The Dictator
- The Dark Knight
- The Dark Knight Rises
- The Forever Purge
- The Last of Us
- The Girl with all the gifts
- The Greatest Showman
- The Man from Toronto
- The Mummy
- The Pope's Exorcist
- The Purge
- The Walking Dead
- The Wailing
- The Garfield Movie
- Top Gun: Maverick
- Toy Story 1 & 2 & 3 & 4
- Train to busan
- Valkyrie
- War for the planet of the apes
- Kingdom of the planets of the apes
- War of the worlds
- World War Z
- Zombieland
- Zombieland: Double Tap
- Zom 100: Bucket List of the Dead
- Zootopia
